# version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: eventhub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: eventhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: eventhub_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/eventhub
      - JWT_ACCESS_SECRET=sekret_i_gjate_ndrro
      - JWT_REFRESH_SECRET=sekret_tjeter_ndrro
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: eventhub_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: