"""sync is_approved pending_reason notifications

Revision ID: 26016f945c47
Revises: 6bbca78a24b4
Create Date: 2026-06-22 12:51:25.877687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26016f945c47'
down_revision: Union[str, None] = '6bbca78a24b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
