"""sync models

Revision ID: c8cd11e6cc41
Revises: 
Create Date: 2026-06-12 18:21:24.189228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cd11e6cc41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.drop_constraint('rsvps_user_id_event_id_key', 'rsvps', type_='unique')
    op.create_index(op.f('ix_rsvps_id'), 'rsvps', ['id'], unique=False)
    op.create_unique_constraint('uq_user_event_rsvp', 'rsvps', ['user_id', 'event_id'])
    op.add_column('users', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'refresh_token')
    op.drop_constraint('uq_user_event_rsvp', 'rsvps', type_='unique')
    op.drop_index(op.f('ix_rsvps_id'), table_name='rsvps')
    op.create_unique_constraint('rsvps_user_id_event_id_key', 'rsvps', ['user_id', 'event_id'])
    op.drop_index(op.f('ix_events_id'), table_name='events')
    # ### end Alembic commands ###
